apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: markets-o11y-prod

labels:
  - pairs:
      app.kubernetes.io/name: markets-o11y
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true

resources:
  # Namespace
  - namespace.yaml

  # PVCs
  - pvcs/pvcs.yaml

  # ConfigMaps
  - configmaps/app-config.yaml
  - configmaps/db-init-scripts.yaml
  - configmaps/worker-config.yaml
  - configmaps/grafana-provisioning.yaml
  - configmaps/grafana-dashboards.yaml
  - configmaps/worker-logs-dashboard.yaml

  # Deployments
  - deployments/timescaledb.yaml
  - deployments/worker.yaml
  - deployments/grafana.yaml

  # Services
  - services/services.yaml
