{
 "title": "Markets",
 "tags": [
  "markets-o11y",
  "finance"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  { "title": "ETFs / Indexes 📦", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "S&P 500 VOO",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, close as value FROM prices WHERE symbol = 'VOO' AND (granularity = 'daily' OR time >= CURRENT_DATE) AND $__timeFilter(time) ORDER BY time"
    }
   ]
  },
  {
   "title": "S&P 500 VOO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT time, symbol, close as value\nFROM prices\nWHERE $__timeFilter(time)\n  AND symbol = 'VOO'\n  AND (granularity = 'daily' OR time >= CURRENT_DATE)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Dow Jones (^DJI)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, close as value FROM prices WHERE symbol = '^DJI' AND (granularity = 'daily' OR time >= CURRENT_DATE) AND $__timeFilter(time) ORDER BY time"
    }
   ]
  },
  {
   "title": "Dow Jones (^DJI)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT time, symbol, close as value\nFROM prices\nWHERE $__timeFilter(time)\n  AND symbol = '^DJI'\n  AND (granularity = 'daily' OR time >= CURRENT_DATE)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Vanguard FTSE All-World / VWRD.L",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, close as value FROM prices WHERE symbol = 'VWRD.L' AND (granularity = 'daily' OR time >= CURRENT_DATE) AND $__timeFilter(time) ORDER BY time"
    }
   ]
  },
  {
   "title": "Vanguard FTSE All-World / VWRD.L",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT time, symbol, close as value\nFROM prices\nWHERE $__timeFilter(time)\n  AND symbol = 'VWRD.L'\n  AND (granularity = 'daily' OR time >= CURRENT_DATE)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Vanguard US Total / VTSAX",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, close as value FROM prices WHERE symbol = 'VTSAX' AND (granularity = 'daily' OR time >= CURRENT_DATE) AND $__timeFilter(time) ORDER BY time"
    }
   ]
  },
  {
   "title": "Vanguard US Total / VTSAX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "rawSql": "SELECT time, symbol, close as value\nFROM prices\nWHERE $__timeFilter(time)\n  AND symbol = 'VTSAX'\n  AND (granularity = 'daily' OR time >= CURRENT_DATE)\nORDER BY time"
    }
   ]
  },
  { "title": "Commodities 🪎 / Crypto ₿", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Gold (GC=F)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, close as value FROM prices WHERE symbol = 'GC=F' AND (granularity = 'daily' OR time >= CURRENT_DATE) AND $__timeFilter(time) ORDER BY time"
    }
   ]
  },
  {
   "title": "Gold (GC=F)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "rawSql": "SELECT time, symbol, close as value\nFROM prices\nWHERE $__timeFilter(time)\n  AND symbol = 'GC=F'\n  AND (granularity = 'daily' OR time >= CURRENT_DATE)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Silver (SI=F)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, close as value FROM prices WHERE symbol = 'SI=F' AND (granularity = 'daily' OR time >= CURRENT_DATE) AND $__timeFilter(time) ORDER BY time"
    }
   ]
  },
  {
   "title": "Silver (SI=F)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "rawSql": "SELECT time, symbol, close as value\nFROM prices\nWHERE $__timeFilter(time)\n  AND symbol = 'SI=F'\n  AND (granularity = 'daily' OR time >= CURRENT_DATE)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Crude Oil (CL=F)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, close as value FROM prices WHERE symbol = 'CL=F' AND (granularity = 'daily' OR time >= CURRENT_DATE) AND $__timeFilter(time) ORDER BY time"
    }
   ]
  },
  {
   "title": "Crude Oil (CL=F)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 71 },
   "targets": [
    {
     "rawSql": "SELECT time, symbol, close as value\nFROM prices\nWHERE $__timeFilter(time)\n  AND symbol = 'CL=F'\n  AND (granularity = 'daily' OR time >= CURRENT_DATE)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Bitcoin (BTC-USD)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, close as value FROM prices WHERE symbol = 'BTC-USD' AND (granularity = 'daily' OR time >= CURRENT_DATE) AND $__timeFilter(time) ORDER BY time"
    }
   ]
  },
  {
   "title": "Bitcoin (BTC-USD)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 82 },
   "targets": [
    {
     "rawSql": "SELECT time, symbol, close as value\nFROM prices\nWHERE $__timeFilter(time)\n  AND symbol = 'BTC-USD'\n  AND (granularity = 'daily' OR time >= CURRENT_DATE)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Ethereum (ETH-USD)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, close as value FROM prices WHERE symbol = 'ETH-USD' AND (granularity = 'daily' OR time >= CURRENT_DATE) AND $__timeFilter(time) ORDER BY time"
    }
   ]
  },
  {
   "title": "Ethereum (ETH-USD)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 93 },
   "targets": [
    {
     "rawSql": "SELECT time, symbol, close as value\nFROM prices\nWHERE $__timeFilter(time)\n  AND symbol = 'ETH-USD'\n  AND (granularity = 'daily' OR time >= CURRENT_DATE)\nORDER BY time"
    }
   ]
  },
  { "title": "Tech 💾", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "AAPL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, close as value FROM prices WHERE symbol = 'AAPL' AND (granularity = 'daily' OR time >= CURRENT_DATE) AND $__timeFilter(time) ORDER BY time"
    }
   ]
  },
  {
   "title": "AAPL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 105 },
   "targets": [
    {
     "rawSql": "SELECT time, symbol, close as value\nFROM prices\nWHERE $__timeFilter(time)\n  AND symbol = 'AAPL'\n  AND (granularity = 'daily' OR time >= CURRENT_DATE)\nORDER BY time"
    }
   ]
  },
  {
   "title": "TSLA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, close as value FROM prices WHERE symbol = 'TSLA' AND (granularity = 'daily' OR time >= CURRENT_DATE) AND $__timeFilter(time) ORDER BY time"
    }
   ]
  },
  {
   "title": "TSLA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 116 },
   "targets": [
    {
     "rawSql": "SELECT time, symbol, close as value\nFROM prices\nWHERE $__timeFilter(time)\n  AND symbol = 'TSLA'\n  AND (granularity = 'daily' OR time >= CURRENT_DATE)\nORDER BY time"
    }
   ]
  },
  {
   "title": "NVDA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, close as value FROM prices WHERE symbol = 'NVDA' AND (granularity = 'daily' OR time >= CURRENT_DATE) AND $__timeFilter(time) ORDER BY time"
    }
   ]
  },
  {
   "title": "NVDA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 127 },
   "targets": [
    {
     "rawSql": "SELECT time, symbol, close as value\nFROM prices\nWHERE $__timeFilter(time)\n  AND symbol = 'NVDA'\n  AND (granularity = 'daily' OR time >= CURRENT_DATE)\nORDER BY time"
    }
   ]
  },
  {
   "title": "GOOGL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, close as value FROM prices WHERE symbol = 'GOOGL' AND (granularity = 'daily' OR time >= CURRENT_DATE) AND $__timeFilter(time) ORDER BY time"
    }
   ]
  },
  {
   "title": "GOOGL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 138 },
   "targets": [
    {
     "rawSql": "SELECT time, symbol, close as value\nFROM prices\nWHERE $__timeFilter(time)\n  AND symbol = 'GOOGL'\n  AND (granularity = 'daily' OR time >= CURRENT_DATE)\nORDER BY time"
    }
   ]
  },
  {
   "title": "AMZN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, close as value FROM prices WHERE symbol = 'AMZN' AND (granularity = 'daily' OR time >= CURRENT_DATE) AND $__timeFilter(time) ORDER BY time"
    }
   ]
  },
  {
   "title": "AMZN",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 149 },
   "targets": [
    {
     "rawSql": "SELECT time, symbol, close as value\nFROM prices\nWHERE $__timeFilter(time)\n  AND symbol = 'AMZN'\n  AND (granularity = 'daily' OR time >= CURRENT_DATE)\nORDER BY time"
    }
   ]
  },
  {
   "title": "ORCL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, close as value FROM prices WHERE symbol = 'ORCL' AND (granularity = 'daily' OR time >= CURRENT_DATE) AND $__timeFilter(time) ORDER BY time"
    }
   ]
  },
  {
   "title": "ORCL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 160 },
   "targets": [
    {
     "rawSql": "SELECT time, symbol, close as value\nFROM prices\nWHERE $__timeFilter(time)\n  AND symbol = 'ORCL'\n  AND (granularity = 'daily' OR time >= CURRENT_DATE)\nORDER BY time"
    }
   ]
  },
  {
   "title": "AMD",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, close as value FROM prices WHERE symbol = 'AMD' AND (granularity = 'daily' OR time >= CURRENT_DATE) AND $__timeFilter(time) ORDER BY time"
    }
   ]
  },
  {
   "title": "AMD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 171 },
   "targets": [
    {
     "rawSql": "SELECT time, symbol, close as value\nFROM prices\nWHERE $__timeFilter(time)\n  AND symbol = 'AMD'\n  AND (granularity = 'daily' OR time >= CURRENT_DATE)\nORDER BY time"
    }
   ]
  },
  {
   "title": "MSFT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 179 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, close as value FROM prices WHERE symbol = 'MSFT' AND (granularity = 'daily' OR time >= CURRENT_DATE) AND $__timeFilter(time) ORDER BY time"
    }
   ]
  },
  {
   "title": "MSFT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 182 },
   "targets": [
    {
     "rawSql": "SELECT time, symbol, close as value\nFROM prices\nWHERE $__timeFilter(time)\n  AND symbol = 'MSFT'\n  AND (granularity = 'daily' OR time >= CURRENT_DATE)\nORDER BY time"
    }
   ]
  },
  {
   "title": "INTC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, close as value FROM prices WHERE symbol = 'INTC' AND (granularity = 'daily' OR time >= CURRENT_DATE) AND $__timeFilter(time) ORDER BY time"
    }
   ]
  },
  {
   "title": "INTC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 193 },
   "targets": [
    {
     "rawSql": "SELECT time, symbol, close as value\nFROM prices\nWHERE $__timeFilter(time)\n  AND symbol = 'INTC'\n  AND (granularity = 'daily' OR time >= CURRENT_DATE)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Boeing / BA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 201 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, close as value FROM prices WHERE symbol = 'BA' AND (granularity = 'daily' OR time >= CURRENT_DATE) AND $__timeFilter(time) ORDER BY time"
    }
   ]
  },
  {
   "title": "Boeing / BA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 204 },
   "targets": [
    {
     "rawSql": "SELECT time, symbol, close as value\nFROM prices\nWHERE $__timeFilter(time)\n  AND symbol = 'BA'\n  AND (granularity = 'daily' OR time >= CURRENT_DATE)\nORDER BY time"
    }
   ]
  },
  {
   "title": "ETSY",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 212 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, close as value FROM prices WHERE symbol = 'ETSY' AND (granularity = 'daily' OR time >= CURRENT_DATE) AND $__timeFilter(time) ORDER BY time"
    }
   ]
  },
  {
   "title": "ETSY",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 215 },
   "targets": [
    {
     "rawSql": "SELECT time, symbol, close as value\nFROM prices\nWHERE $__timeFilter(time)\n  AND symbol = 'ETSY'\n  AND (granularity = 'daily' OR time >= CURRENT_DATE)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Currencies 💵",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 223 },
   "collapsed": true,
   "panels": [
    {
     "title": "EUR/TRY",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 224 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT time, close as value FROM prices WHERE symbol = 'EURTRY=X' AND (granularity = 'daily' OR time >= CURRENT_DATE) AND $__timeFilter(time) ORDER BY time"
      }
     ]
    },
    {
     "title": "GBP/USD",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 224 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT time, close as value FROM prices WHERE symbol = 'GBPUSD=X' AND (granularity = 'daily' OR time >= CURRENT_DATE) AND $__timeFilter(time) ORDER BY time"
      }
     ]
    },
    {
     "title": "EUR/USD",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 224 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT time, close as value FROM prices WHERE symbol = 'EURUSD=X' AND (granularity = 'daily' OR time >= CURRENT_DATE) AND $__timeFilter(time) ORDER BY time"
      }
     ]
    },
    {
     "title": "EUR/TRY",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 227 },
     "targets": [
      {
       "rawSql": "SELECT time, symbol, close as value\nFROM prices\nWHERE $__timeFilter(time)\n  AND symbol = 'EURTRY=X'\n  AND (granularity = 'daily' OR time >= CURRENT_DATE)\nORDER BY time"
      }
     ]
    },
    {
     "title": "GBP/USD",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 227 },
     "targets": [
      {
       "rawSql": "SELECT time, symbol, close as value\nFROM prices\nWHERE $__timeFilter(time)\n  AND symbol = 'GBPUSD=X'\n  AND (granularity = 'daily' OR time >= CURRENT_DATE)\nORDER BY time"
      }
     ]
    },
    {
     "title": "EUR/USD",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 227 },
     "targets": [
      {
       "rawSql": "SELECT time, symbol, close as value\nFROM prices\nWHERE $__timeFilter(time)\n  AND symbol = 'EURUSD=X'\n  AND (granularity = 'daily' OR time >= CURRENT_DATE)\nORDER BY time"
      }
     ]
    }
   ]
  }
 ]
}